version: '3.3'
services:
  python3:
    ports:
      - 8000:80
    build: ./src/
    links:
      - db
    stdin_open: true
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
      eTZ: Asia/Tokyo
    stdin_open: true

  