version: '3.3'
services:
  python3:
    container_name: Flask-Project-1
    build:
      context: ./src
    ports:
      - 8000:80
    volumes:
      - ./:/Flask-Project-1
    tty: true
    environment:
      - FLASK_APP=src.run
      - FLASK_ENV=development
    links:
      - mysql

#mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
      eTZ: Asia/Tokyo

  