version: '3.3'
services:
  python3:
    build:
      context: ./src
    ports:
      - 8000:80
    volumes:
      - ./src:/src
    environment:
      - FLASK_APP=src.run:app
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0
    links:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
      eTZ: Asia/Tokyo

  