version: '3'
services:
  db:
    image: mysql:5.7
    container_name: python-db
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      #userパスワード
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=docker
      - TZ=Asia/Tokyo
      #rootパスワード
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    stdin_open: true
      
  #python
  python3:
    container_name: python3
    build:
      context: ./python/
    links:
      - db
    stdin_open: true

  